3.odev/Uniport/Uniport/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using System.Threading;

namespace Uniport.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Change(String languageSelect)
        {
            if (languageSelect != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(languageSelect);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(languageSelect);
            }

            HttpCookie cookie = new HttpCookie("language");
            cookie.Value = languageSelect;
            Response.Cookies.Add(cookie);

            return RedirectToAction("Index","Home");
        }
    }
}

3.odev/Uniport/Uniport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title UniPort</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="../Content/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="../fonts/font-awesome.min.css" type="text/css" media="screen">
    <!-- ek stiller -->
    <link href="../Content/style.css" rel="stylesheet">
    <style>
         .asd:hover
        {
	        text-decoration: none;
	        color: red;
        }
     </style>
    <script type="text/javascript" src="../Scripts/jquery-2.2.3.min.js"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../Scripts/jquery-2.2.3.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../Scripts/bootstrap.min.js"></script>
    <script src="../Scripts/dropdowsnjs.js"> </script>

</head>


<body style="background-color:#ddd; align-content:center;">
   
        <header class="navbar navbar-inverse navbar-top" style="background-color:white; margin-top:0; border-color:transparent;">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <table border="0" style="width:100%; position:relative;">
                        <tr>
                            <td class="baslikkolon1">
                                <h3 style="margin-top:6%;"><baslik1 style="color:red;">Uni</baslik1><baslik2 style="color:orange;">Port</baslik2></h3>
                            </td>
                            <td class="baslikkolon2 asd">
                                <ul class="nav navbar-nav  asd" style="color:snow;">
                                    <li class="asd">@Html.ActionLink(Uniport.Resources.HomeText.Home, "Index", "Home")</li>
                                    <li class="asd">@Html.ActionLink(Uniport.Resources.HomeText.Offers, "ilanlar", "Home")</li>
                                    <li class="asd">@Html.ActionLink(Uniport.Resources.HomeText.Give_Offer, "ilanver", "Home")</li>
                                    <li class="asd">@Html.ActionLink(Uniport.Resources.HomeText.On_Sale, "satistakiler", "Home")</li>
                                    <li class="asd">@Html.ActionLink(Uniport.Resources.HomeText.About_Us, "hakkimizda", "Home")</li>
                                </ul>
                            </td>
                            <td>
                                <div class="col-md-3 ">
                                    
                                    <ul class="nav navbar-nav  asd" style="color:red;">
                                      <asd style="color:red;">  @Html.ActionLink("English", "Change", "Language", new { languageSelect = "en" }, null)
                                        @Html.ActionLink("Türkçe", "Change", "Language", new { languageSelect = "tr" }, null)
                                        </asd>
                                    </ul>
                                   
                                </div>
                             </td>                                
                                
                        </tr>
                    </table>
                   
                    <!--üstteki xs de kaybolan başlık yazısı degistirilecek-->
                </div><!-- /.navbar-collapse if else al eger girisyapıldıysa 1 degeri yollansın 1 degeri geldiyse kaybolsun -->
            </div><!-- /.container -->
        </header>


        <div class="col-xs-3 col-md-2 col-lg-2" style=" margin-top:-4%"> <img src="~/resim/21bf8be6-1c9d-4901-87e2-b2d7bd8a941c.png" title="Hoşgeldiniz" class="logoresim" style="width:200px; margin-top:-10%"></div>

    <div class="row" style="margin-top:4.5%; margin-left:-5%;">
        <div class="col-md-4 col-xs-5 col-lg-4" style="margin-top:0%;">
            <form method="post" action="/Home/satistakiler">


                <input class="arama" type="text" id="loginasd" placeholder="Buna Bakmıştım..." style=" border-radius:6px;">


            </form>

        </div>


        <div class="col-md-2 col-xs-1 col-lg-2" style="height:30px; margin-top:0.1%; margin-left:-3.3%; ">
            <div class="wrapper-demo">
                <div id="dd" class="wrapper-dropdown-1" tabindex="1">
                    <span>Kategori</span>
                    <ul class="dropdown" tabindex="1">
                        <li><a href="#">Giyim</a></li>
                        <li><a href="#">Elektronik</a></li>
                        <li><a href="#">Bilgisayar</a></li>
                        <li><a href="#">Ev</a></li>
                        <li><a href="#">Araba</a></li>
                        <li><a href="#">Aksesuar</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-4  col-xs-11 col-lg-3 " style="margin-top:-0.5%; ">
          
               @if (Session["email"] == null)
                {
                    @Html.Raw(
                  "<form method='post' action='/Home/Index' align='right'>" +

                      "<input type='text' id='logintx' placeholder='Email Id' name='email'>" +
                      "<input type='password' id='passwordtx' name='sifre' placeholder='***'>" +
                      "<input type='submit' value='Login' id='lbtn'></br>" +
                      "<uyesif class='uyesif'>  <a class='uyeol'  href='/Home/kaydol'>Üye OL</a> <a class='sifremiunuttum' href='#'>Şifremi Unuttum</a></uyesif>" +
                 " </form>");

                }
                else
                {

                    @Html.Raw("Hosgeldiniz " + Session["email"].ToString() + "<form method='post' action='/Home/cikis' align='right'>" +
           "<input type='submit' value='Cikis' id='lbtn'></br> </form>" + "<form method='post' action='/Home/sepetim' align='right'>" +
           "<input type='submit' value='Sepetim' id='lbtn'></br> </form>");
                }
            
           
        </div>
    </div>
            <!--üst kısım-->
            @RenderBody()
            <hr />

            <footer>

                <div class="copyr col-md-10  col-xs-10 col-lg-10">

                    <div class="container  " style="background-color:#e5eabf; padding:20px; border-radius:100px; ">

                        <div class="col-md-9 text-info  col-xs-9 col-lg-9 ">

                            <strong>Copyright &copy; Okumuş Company</strong>

                        </div>

                    </div>
                </div>

            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>